apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: documents
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - backend:
              serviceName: documents
              servicePort: 8515
            path: /
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: esb-cert
