apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: documents
  name: documents
spec:
  ports:
    - name: http
      port: 8515
      protocol: TCP
      targetPort: 8515
  selector:
    app.kubernetes.io/name: documents
  sessionAffinity: None
  type: ClusterIP
