replicaCount: 1

image:
  repository: quay.io/opsway/documents
  pullPolicy: Always
  tag: latest

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: default
      paths:
        - "/"
  tls:
    - secretName: default
      hosts:
        - "default"

nodeSelector: {}
